apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-secrets-plugin
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-secrets-plugin
