apiVersion: v1
kind: Secret
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  plugin.argocd-secrets-plugin.token: "mySuperSecretToken"